# KataCore StartKit v1 - Production Docker Compose
# Clean and minimal configuration for production deployment

version: '3.8'

services:
  # NestJS API Service
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    image: katacore/api:${API_VERSION:-latest}
    container_name: katacore-api-prod
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - "${API_PORT:-3001}:3001"
    environment:
      # Core Configuration
      NODE_ENV: production
      API_PORT: 3001
      LOG_LEVEL: ${LOG_LEVEL:-info}
      
      # Database Connection
      DATABASE_URL: ${DATABASE_URL}
      
      # Redis Connection
      REDIS_URL: ${REDIS_URL}
      
      # Authentication
      JWT_SECRET: ${JWT_SECRET}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      
      # MinIO Configuration
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_USE_SSL: ${MINIO_USE_SSL:-false}
      
      # CORS Configuration
      CORS_ORIGIN: ${CORS_ORIGIN}
      
    networks:
      - katacore-network
    volumes:
      - api_logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: ${HEALTH_CHECK_INTERVAL:-30s}
      timeout: ${HEALTH_CHECK_TIMEOUT:-10s}
      retries: ${HEALTH_CHECK_RETRIES:-3}
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Next.js Site Service
  site:
    build:
      context: ./site
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    image: katacore/site:${SITE_VERSION:-latest}
    container_name: katacore-site-prod
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - "${SITE_PORT:-3000}:3000"
    environment:
      # Core Configuration
      NODE_ENV: production
      PORT: 3000
      
      # API Configuration
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
      NEXT_PUBLIC_MINIO_ENDPOINT: ${NEXT_PUBLIC_MINIO_ENDPOINT}
      INTERNAL_API_URL: ${INTERNAL_API_URL:-http://api:3001}
      
    networks:
      - katacore-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: ${HEALTH_CHECK_INTERVAL:-30s}
      timeout: ${HEALTH_CHECK_TIMEOUT:-10s}
      retries: ${HEALTH_CHECK_RETRIES:-3}
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: katacore-postgres-prod
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
    networks:
      - katacore-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: katacore-redis-prod
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    networks:
      - katacore-network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    container_name: katacore-minio-prod
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL}
    command: server /data --console-address ":9001"
    networks:
      - katacore-network
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # pgAdmin Web Interface
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: katacore-pgadmin-prod
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    networks:
      - katacore-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/misc/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  katacore-network:
    driver: bridge
    name: katacore-prod-network

volumes:
  # Application data
  postgres_data:
    name: katacore-postgres-prod-data
  redis_data:
    name: katacore-redis-prod-data
  minio_data:
    name: katacore-minio-prod-data
  pgadmin_data:
    name: katacore-pgadmin-prod-data
  
  # Application logs
  api_logs:
    name: katacore-api-prod-logs
