#!/bin/bash

# 🔧 Next.js v15 Environment Setup Script
# Tự động cấu hình environment variables tối ưu

echo "🔧 Setting up optimized environment variables..."
echo "================================================"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

log() {
    echo -e "${BLUE}[SETUP]${NC} $1"
}

success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

# Backup existing .env.local if it exists
if [ -f ".env.local" ]; then
    cp .env.local .env.local.backup.$(date +%Y%m%d_%H%M%S)
    warning "Backed up existing .env.local"
fi

# Create optimized .env.local
log "Creating optimized .env.local..."

cat > .env.local << 'EOF'
# 🚀 Next.js v15 Optimized Environment Configuration
# Generated by optimize-environment.sh

# ========== NEXT.JS OPTIMIZATION ==========
# Disable telemetry for faster startup
NEXT_TELEMETRY_DISABLED=1

# Performance flags
NEXT_PRIVATE_STANDALONE=true
NEXT_PRIVATE_DEBUG_CACHE=false
NEXT_PRIVATE_OPTIMIZE_FONTS=true
NEXT_PRIVATE_OPTIMIZE_IMAGES=true
NEXT_PRIVATE_DISABLE_SOURCEMAPS=true

# Webpack optimization
WEBPACK_OPTIMIZE_MINIMIZE=true

# ========== NODE.JS OPTIMIZATION ==========
# Memory optimization (increase if needed)
NODE_OPTIONS=--max-old-space-size=2048 --max-semi-space-size=1024

# V8 performance flags
NODE_ENV=development

# ========== PRISMA OPTIMIZATION ==========
# Use query engine library for better performance
PRISMA_QUERY_ENGINE_LIBRARY=1
PRISMA_GENERATE_SKIP_AUTOINSTALL=true

# ========== PWA OPTIMIZATION ==========
# Disable PWA in development for faster builds
DISABLE_PWA_IN_DEVELOPMENT=true

# ========== DATABASE CONFIGURATION ==========
# Default local development database
DATABASE_URL="postgresql://username:password@localhost:5432/tazagroup_dev"

# ========== AUTHENTICATION CONFIGURATION ==========
# JWT secrets (replace with your own secure values)
JWT_SECRET="your-super-secure-jwt-secret-here-replace-in-production"
NEXTAUTH_SECRET="your-nextauth-secret-here-replace-in-production"
NEXTAUTH_URL="http://localhost:3900"

# ========== SOCIAL AUTH CONFIGURATION ==========
# Facebook Login (replace with your app credentials)
FACEBOOK_APP_ID="your-facebook-app-id"
FACEBOOK_APP_SECRET="your-facebook-app-secret"

# Google Login (optional)
GOOGLE_CLIENT_ID="your-google-client-id"
GOOGLE_CLIENT_SECRET="your-google-client-secret"

# ========== API OPTIMIZATION ==========
# Rate limiting
API_RATE_LIMIT_MAX=100
API_RATE_LIMIT_WINDOW=60000

# Cache settings
API_CACHE_TTL=300
STATIC_CACHE_TTL=3600

# ========== LOGGING CONFIGURATION ==========
# Log levels: error, warn, info, debug
LOG_LEVEL=info
ENABLE_REQUEST_LOGGING=false

# ========== PERFORMANCE MONITORING ==========
# Enable performance metrics
ENABLE_PERFORMANCE_METRICS=true
ENABLE_MEMORY_MONITORING=false

# ========== DEVELOPMENT CONFIGURATION ==========
# Port configuration
PORT=3900
DEV_PORT=3900

# Hot reload optimization
FAST_REFRESH=true
WATCHPACK_POLLING=false

# ========== BUILD OPTIMIZATION ==========
# Bundle analyzer
ANALYZE=false

# Compression
ENABLE_GZIP=true
ENABLE_BROTLI=true

# ========== SECURITY CONFIGURATION ==========
# CORS settings
CORS_ORIGIN="http://localhost:3900"

# Session security
SESSION_TIMEOUT=86400
SECURE_COOKIES=false

# ========== ADDITIONAL OPTIMIZATION FLAGS ==========
# TypeScript performance
TS_NODE_TRANSPILE_ONLY=true
TS_NODE_SKIP_PROJECT=true

# React optimization
REACT_EDITOR=code
BROWSER=none

# Suppress experimental warnings
SUPPRESS_NO_CONFIG_WARNING=true
EOF

success "Created optimized .env.local"

# Create production environment template
log "Creating production environment template..."

cat > .env.production.template << 'EOF'
# 🚀 Next.js v15 Production Environment Template
# Copy to .env.production and update values for production deployment

# ========== NEXT.JS PRODUCTION ==========
NODE_ENV=production
NEXT_TELEMETRY_DISABLED=1
NEXT_PRIVATE_STANDALONE=true

# ========== NODE.JS PRODUCTION ==========
NODE_OPTIONS=--max-old-space-size=4096

# ========== DATABASE PRODUCTION ==========
# Replace with your production database URL
DATABASE_URL="postgresql://user:password@your-production-db:5432/tazagroup_prod"

# ========== AUTHENTICATION PRODUCTION ==========
# Generate secure secrets for production
JWT_SECRET="REPLACE-WITH-SECURE-RANDOM-STRING-64-CHARS-MIN"
NEXTAUTH_SECRET="REPLACE-WITH-SECURE-RANDOM-STRING-64-CHARS-MIN"
NEXTAUTH_URL="https://your-production-domain.com"

# ========== SOCIAL AUTH PRODUCTION ==========
FACEBOOK_APP_ID="your-production-facebook-app-id"
FACEBOOK_APP_SECRET="your-production-facebook-app-secret"

# ========== SECURITY PRODUCTION ==========
CORS_ORIGIN="https://your-production-domain.com"
SECURE_COOKIES=true
SESSION_TIMEOUT=43200

# ========== MONITORING PRODUCTION ==========
ENABLE_PERFORMANCE_METRICS=true
ENABLE_MEMORY_MONITORING=true
LOG_LEVEL=warn

# ========== CDN & ASSETS ==========
NEXT_PUBLIC_CDN_URL="https://your-cdn-domain.com"
NEXT_PUBLIC_STATIC_URL="https://your-static-assets.com"
EOF

success "Created production environment template"

# Create environment validation script
log "Creating environment validation script..."

cat > validate-env.js << 'EOF'
#!/usr/bin/env node

// 🔍 Environment Variables Validation Script
console.log('🔍 Validating environment configuration...\n');

const requiredVars = {
  development: [
    'DATABASE_URL',
    'JWT_SECRET',
    'NEXTAUTH_SECRET',
    'NEXTAUTH_URL'
  ],
  production: [
    'DATABASE_URL', 
    'JWT_SECRET',
    'NEXTAUTH_SECRET', 
    'NEXTAUTH_URL',
    'NODE_ENV'
  ]
};

const optionalVars = [
  'FACEBOOK_APP_ID',
  'FACEBOOK_APP_SECRET',
  'GOOGLE_CLIENT_ID',
  'GOOGLE_CLIENT_SECRET'
];

const performanceVars = [
  'NEXT_TELEMETRY_DISABLED',
  'NODE_OPTIONS',
  'PRISMA_QUERY_ENGINE_LIBRARY'
];

function validateEnvironment() {
  const env = process.env.NODE_ENV || 'development';
  const required = requiredVars[env] || requiredVars.development;
  
  console.log(`Environment: ${env.toUpperCase()}`);
  console.log('=' .repeat(40));
  
  // Check required variables
  console.log('\n📋 Required Variables:');
  let missingRequired = [];
  
  required.forEach(varName => {
    const value = process.env[varName];
    if (!value) {
      console.log(`❌ ${varName}: Missing`);
      missingRequired.push(varName);
    } else if (value.includes('REPLACE-WITH') || value.includes('your-')) {
      console.log(`⚠️  ${varName}: Needs configuration`);
    } else {
      console.log(`✅ ${varName}: Configured`);
    }
  });
  
  // Check optional variables
  console.log('\n🔧 Optional Variables:');
  optionalVars.forEach(varName => {
    const value = process.env[varName];
    if (!value) {
      console.log(`⏸️  ${varName}: Not set`);
    } else if (value.includes('your-')) {
      console.log(`⚠️  ${varName}: Needs configuration`);  
    } else {
      console.log(`✅ ${varName}: Configured`);
    }
  });
  
  // Check performance variables
  console.log('\n🚀 Performance Variables:');
  performanceVars.forEach(varName => {
    const value = process.env[varName];
    if (value) {
      console.log(`✅ ${varName}: ${value}`);
    } else {
      console.log(`⏸️  ${varName}: Not set`);
    }
  });
  
  // Summary
  console.log('\n' + '=' .repeat(40));
  if (missingRequired.length > 0) {
    console.log(`❌ Missing ${missingRequired.length} required variable(s)`);
    console.log('Please configure:', missingRequired.join(', '));
    process.exit(1);
  } else {
    console.log('✅ All required variables are configured');
    console.log('🚀 Environment is ready!');
  }
}

validateEnvironment();
EOF

chmod +x validate-env.js
success "Created environment validation script"

# Create quick setup guide
log "Creating quick setup guide..."

cat > ENV_SETUP_GUIDE.md << 'EOF'
# 🔧 Environment Setup Guide

## Quick Start

1. **Automatic Setup** (Recommended):
   ```bash
   ./setup-environment.sh
   ```

2. **Manual Setup**:
   - Copy `.env.local` and update values
   - Run `node validate-env.js` to check configuration

## Environment Files

### Development (`.env.local`)
- Auto-generated with optimized defaults
- Update database URL and auth secrets
- Ready for local development

### Production (`.env.production`)
- Use `.env.production.template` as starting point
- Generate secure secrets (64+ characters)
- Update all "REPLACE-WITH" and "your-" values

## Validation

Run environment validation:
```bash
node validate-env.js
```

## Required Updates

### 1. Database URL
```bash
DATABASE_URL="postgresql://username:password@localhost:5432/tazagroup_dev"
```

### 2. JWT Secrets
Generate secure secrets:
```bash
# Generate random secret
openssl rand -base64 64

# Or use Node.js
node -e "console.log(require('crypto').randomBytes(64).toString('base64'))"
```

### 3. Facebook Auth (Optional)
- Get credentials from [Facebook Developers](https://developers.facebook.com/)
- Update `FACEBOOK_APP_ID` and `FACEBOOK_APP_SECRET`

## Performance Variables

These are automatically set for optimization:
- `NEXT_TELEMETRY_DISABLED=1` - Faster startup
- `NODE_OPTIONS=--max-old-space-size=2048` - Memory optimization
- `PRISMA_QUERY_ENGINE_LIBRARY=1` - Faster database queries

## Security Notes

⚠️ **Important**:
- Never commit `.env.local` or `.env.production` to version control
- Use different secrets for development and production
- Regularly rotate production secrets
- Use HTTPS in production (`SECURE_COOKIES=true`)

## Troubleshooting

### Database Connection Issues
1. Check if PostgreSQL is running
2. Verify database URL format
3. Test connection: `npm run test:db`

### Build Issues
1. Run `node validate-env.js`
2. Check for missing required variables
3. Ensure NODE_OPTIONS are set correctly

### Performance Issues
1. Verify `NEXT_TELEMETRY_DISABLED=1`
2. Check Node.js memory settings
3. Enable performance monitoring in production
EOF

success "Created environment setup guide"

# Final instructions
echo
echo "================================================"
echo -e "${GREEN}🎉 Environment Setup Complete!${NC}"
echo "================================================"
echo
echo "📋 Files Created:"
echo "  • .env.local - Development configuration"
echo "  • .env.production.template - Production template"
echo "  • validate-env.js - Environment validator"
echo "  • ENV_SETUP_GUIDE.md - Setup guide"
echo
echo "🔧 Next Steps:"
echo "  1. Update database URL in .env.local"
echo "  2. Generate secure JWT secrets"
echo "  3. Configure Facebook auth (optional)"
echo "  4. Run: node validate-env.js"
echo
echo "📖 Read ENV_SETUP_GUIDE.md for detailed instructions"
echo

# Ask if user wants to validate now
read -p "Would you like to validate the environment now? (y/N): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    node validate-env.js
fi

success "Environment setup completed!"
